### PR TITLE
Adding support for Python 11

### PR DESCRIPTION
**Pull request by ZhymabekRoman**
Bumping aiohttp version. There is some test fails, idk maybe it's not related to Python version. Thanks!

### CODE REVIEW

**Comment by TurboKach** [comment]
are you sure it's safe for any other packages inside? have you tested?

**Comment by ZhymabekRoman** [comment]
Yes, I tested, all works as expected

**Comment by TurboKach** [comment]
@HMaker plz take a look when you have a time

btw it's a good time to test and bump CDP supported version

**Comment by HMaker** [comment]
Thanks for the PR. I also updated the CDP version to Chrome 117.

**Pull request merged**
